name: shared
description: 
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: ../core/

dev_dependencies:
  pedantic: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
  # assets:
  #   - ../assets/images/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: ../assets/fonts/Roboto/Roboto-Thin.ttf
  #         weight: 100
  #       - asset: ../assets/fonts/Roboto/Roboto-Light.ttf
  #         weight: 300
  #       - asset: ../assets/fonts/Roboto/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: ../assets/fonts/Roboto/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: ../assets/fonts/Roboto/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: ../assets/fonts/Roboto/Roboto-Black.ttf
  #         weight: 900